### ISSUE TITLE
awesome work - however...

### ISSUE THREAD

**Issue by audstanley** [bestbug456/EDP#1]
I'm trying to write to the 2.13v2 (and using epd as a library), and for the life of me I can't figure out why a 250x122 [as advertised] pixel display doesn't take a byte array that is length 30500 (each pixel from range 0-255 [am i wrong on this?]).  I've used your main example and it looks perfect on the display, but when i fmt.Prinln the length of the byte array, it is of length 4000. Can you help me wrap my head around why this is the case?

**Comment by audstanley** [comment]
okay, i think i get the GetBuffer function - super awesome - don't know why i didn't look more closely at that function.  I'm working on a single binary for arm6, and arm7 that just takes a stringified JSON-LD Linux pipe to display text to the display.  Super good work.. I'm going to use your project as a way to better understand SPI and communicating with device registers. Seriously, thanks for this driver.  I'm learning a lot. :slightly_smiling_face: GoLang rocks.  Still confused on the pixel math that you have, but I'll log to console to see if i can wrap my brain around the way in which a png turns into these grey scale style binary arrays - couldn't there just be a GetBuffer function that just returns an 8bit grey scale?  If so, I'll add to this code and do a PR.  :open_hands:

**Comment by bestbug456** [comment]
Hi Richard,

At the moment I can't check GitHub but I'll give feedback as soon as I can look again at the code. For the different size I read the example code in python ad port 1 to 1 each line of their code, then I try to optimize where possibile. The size of the buffer come right from their code example if I remember correctly. If you think the code can be improved feel free to open the PR, I'll check it back when I will be able to use GitHub again.

Cheers!

Bestbug

**Comment by bestbug456** [comment]
Hello again @audstanley,

I'm again able to access to github, hence I've restudy a little bit the code. The size of the buffer, as you rightly say, is defined in GetBuffer function. The math behind that is port 1 to 1 from the official python driver of waweshare. I try back in the day to understand how or if we could improve the readability of that part, sadly since I was not able to find a clear description of why we have to do this I've just port in GO the code. Sadly I think you have to take this function as "dogma" and port to your solution. That said I'm not still sure about the code extension you are talking about. Can you explain a little bit more the problem that you have?

Cheers

**Comment by audstanley** [comment]
I guess dogma might just have to be the way to go for now (at least for the 2.13v2). 😊 - I was thinking about getting a larger waveshare display, but I want to stick with GoLang for driving the next display I get and not python or c (preferably) for building some other project.  I guess just having more comments in the driver code is what I was hoping for, but no worries.
